### ISSUE TITLE
AppCenterLogger constructor fails

### ISSUE THREAD

**Issue by maxal1917** [dansiegel/Prism.Plugin.Logging#10] opened 2018-07-09 03:35 UTC
"Exception occurred while: Calling constructor Prism.Logging.AppCenter.AppCenterLogger().
Exception is: NullReferenceException - Object reference not set to an instance of an object."

Cannot initialize instance of AppCenterLogger.

Version 1.1.0.85.

**Comment by dansiegel** [comment] 2018-07-09 03:36
Closing as a duplicate of #9

**Closed as completed by dansiegel** 2018-07-09 03:36 UTC
